name: Build Latest Kernel for Vanilla

on:
  workflow_dispatch:

env:
  UPLOAD_DIR: true
  UPLOAD_RELEASE: true
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Compile the kernel
      id: compile
      run: |
        sudo apt install fakeroot build-essential bc bison flex libelf-dev libssl-dev xz-utils ncurses-dev rpm
        mkdir out
        mkdir ../output
        kernel_ver=$(make O=out kernelversion --no-print-directory)
        make O=out vanilla_defconfig
        echo -e "$(nproc) thread compile"
        time make O=out -j$(nproc)
        time make O=out modules -j$(nproc)
        time make O=out rpm-pkg -j$(nproc)
        cp -r ~/rpmbuild/RPMS/x86_64/* ../output/
        echo '::set-output name=action_echo::enabled'
        echo "::set-output name=status::success"
        echo "FILE_DATE=Kernel_Vanilla_$kernel_ver_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      run: df -hT

    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.FILE_DATE }}
        path: ../output

    - name: Generate release tag
      id: tag
      run: |
        kernel_ver=$(make O=out kernelversion --no-print-directory)
        echo '::set-output name=action_echo::enabled'
        echo "::set-output name=release_tag::Kernel_Vanilla_${kernel_ver}_$(date +"%Y.%m.%d-%H%M")"
        touch release.txt
        echo "Kernel_Vanilla_${kernel_ver}_$(date +"%Y.%m.%d-%H%M")" >> release.txt
        echo '::set-output name=action_echo::enabled'
        echo "::set-output name=status::success"

    - name: Upload kernel to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ../output/*
