name: Build Latest Kernel for Vanilla

on:
  workflow_dispatch:

env:
  UPLOAD_DIR: true
  UPLOAD_RELEASE: true
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Compile the kernel
      id: compile
      if: steps.code.outputs.status == 'success'
      run: |
        mkdir out
        mkdir ../output
        kernel_ver=$(make O=out kernelversion --no-print-directory)
        make O=out vanilla_defconfig
        echo -e "$(nproc) thread compile"
        time make O=out -j$(nproc)
        time make O=out modules -j$(nproc)
        cd  && mv *.deb /workdir/upload
        tar -cvf ../output/output.tar out/arch/x86/boot
        echo '::set-output name=action_echo::enabled'
        echo "::set-output name=status::success"
        echo "FILE_DATE=Kernel_Vanilla_$kernel_ver_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled()) && steps.compile.outputs.status == 'success'
      run: df -hT

    - name: Upload
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_DIR == 'true'
      with:
        name: ${{ env.FILE_DATE }}
        path: ../output
