name: Build Latest Kernel for Vanilla

on:
  workflow_dispatch:
  #schedule:
    #- cron: "36 20 * * 1,4"
   # inputs:
    #  ssh:
     #   description: 'SSH connection to Actions'
      #  required: false
       # default: 'false'

env:
  UPLOAD_DIR: true
  UPLOAD_RELEASE: true
  UPLOAD_WETRANSFER: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/qctt/kernelbuild:ubuntu20
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
     
    - name: Check
      id: check
      run: |
        ls
        pwd
        ls ..
